-- local image = require 'image'
--
-- local buf = vim.api.nvim_create_buf(false, true)
-- local win = vim.api.nvim_open_win(buf, false, {
--   relative = 'editor',
--   width = 10,
--   height = 5,
--   row = 1,
--   col = vim.o.columns - 12,
--   style = 'minimal',
--   border = 'rounded',
--   focusable = false,
--   zindex = 200,
-- })
--
-- local img = image.from_file('~/Pictures/cat.png', {
--   buffer = buf,
--   window = win,
--   with_virtual_padding = true, -- reserves space in buffer for the image
--   x = 0,
--   y = 0,
--   width = 10,
--   height = 5,
-- })
--
-- img:render()
